"""Source of every unit's song lyrics (Bahasa Melayu, sebutan baku), written from that game's own steps.json content.
python tools/songs/lyrics_all.py -> writes games/<id>/assets/lagu.json for every song below (keeps any game not listed).
Structure: chorus after verse 1, then after every two verses, and at the end. Edit here, re-run, then regenerate that song."""
import json, os

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))

# id: (title, style, chorus or None, [verses])
SONGS = {
# ------------------------------------------------------------------ Tahun 1
"T1-U01-kemahiran-saintifik": ("Saintis Cilik", "tadika",
 ["Saintis cilik, saintis cilik", "Memerhati dengan teliti", "Kanta pembesar di tangan", "Sains seronok setiap hari!"],
 [["Mari jadi saintis cilik", "Guna lima deria kita", "Lihat, dengar, sentuh, hidu", "Dan rasa pun deria juga"],
  ["Ikan kecil hendak dipindah", "Guna penyauk dengan cermat", "Spesimen kita kendalikan", "Supaya ia tetap selamat"],
  ["Lakarkan spesimen dengan tepat", "Ceritakan kepada kawan", "Secara lisan, lakaran, tulisan", "Kita berkomunikasi"],
  ["Selesai kerja, cuci peralatan", "Bersihkan dengan cara betul", "Simpan dengan betul dan selamat", "Bilik sains kemas teratur"]]),
"T1-U02-peraturan-bilik-sains": ("Jom Patuhi Peraturan", "dikir",
 ["Bilik Sains, Bilik Sains", "Patuhi peraturannya", "Bersih, kemas dan selamat", "Belajar jadi berkesan"],
 [["Sebelum masuk Bilik Sains", "Apakah yang perlu kita buat?", "Beratur dahulu, beratur dahulu", "Minta kebenaran guru"],
  ["Di dalam Bilik Sains", "Apakah yang dilarang?", "Jangan bergurau, jangan berlari", "Jangan bermain sesuka hati"],
  ["Makan dan minum, makan dan minum", "Dilarang di Bilik Sains", "Sampah jangan masuk ke singki", "Nanti singki tersumbat"]]),
"T1-U03-benda-hidup": ("Ciri Benda Hidup", "pop",
 ["Bernafas, perlukan air dan makanan", "Bergerak, membesar, membiak", "Itulah ciri benda hidup", "Mari kita ingat, kawan!"],
 [["Manusia, pokok dan burung", "Semuanya benda hidup", "Anak patung, kereta dan batu", "Benda bukan hidup"],
  ["Kapal terbang boleh bergerak", "Tetapi tak bernafas, tak membesar", "Bukan benda hidup, ingatlah", "Satu ciri tidak cukup"],
  ["Tikus, kucing hutan, rusa", "Seladang dan gajah", "Dari kecil kepada besar", "Kita susun ikut saiz"],
  ["Makanan, air dan udara", "Keperluan asas benda hidup", "Manusia dan haiwan perlu tempat", "Berlindung dari hujan, panas, bahaya"]]),
"T1-U04-manusia": ("Lihat, Dengar, Hidu, Rasa", "tadika", None,
 [["Lihatlah, dengar, hidu, rasa, hidu, rasa", "Lihatlah, dengar, hidu, rasa, hidu, rasa", "Mata, telinga, hidung, lidah", "Lihatlah, dengar, hidu, rasa, sentuh, sentuh!"],
  ["Matanya warna, saiz, bentuk, saiz, bentuk", "Telinga bunyi, hidung bau, hidung bau", "Lidahnya rasa manis, masam", "Kulitnya kasar, licin, lembut, keras, sentuh!"],
  ["Cermin mata bantu lihat, bantu lihat", "Alat bantu, bantu dengar, bantu dengar", "Gelap-gelita, guna sentuh", "Deria lain boleh bantu, boleh bantu!"]]),
"T1-U07-magnet": ("Paku Oh Paku", "tadika", None,
 [["Paku oh paku, kenapa kau melekat?", "Macam mana aku tak lekat, magnet menarik besi"],
  ["Pensel oh pensel, kenapa kau tak lekat?", "Macam mana aku nak lekat, aku bukannya besi"],
  ["Magnet oh magnet, kenapa kau menolak?", "Macam mana aku tak tolak, kutub kita sama"],
  ["Magnet oh magnet, kenapa kau menarik?", "Macam mana aku tak tarik, kutub kita berlainan"],
  ["Peti oh peti, kenapa pintu rapat?", "Macam mana aku tak rapat, ada magnet di situ"]]),
"T1-U05-haiwan": ("Haiwan dan Tubuhnya", "joget",
 ["Haiwan, haiwan, lihat tubuhnya", "Setiap bahagian ada gunanya", "Kepak, sirip, ekor dan kaki", "Semuanya penting belaka"],
 [["Badak sumbu ada sumbu", "Kura-kura ada cangkerang", "Ikan bersisik, kambing bertanduk", "Rama-rama bersesungut panjang"],
  ["Itik berkaki selaput renang", "Kepak untuk terbang tinggi", "Sirip untuk berenang", "Ekor memandu arah"],
  ["Sumbu, tanduk dan kulit keras", "Untuk mempertahankan diri", "Lembu, kucing, hamster, arnab", "Bulunya halus belaka"],
  ["Lakarkan haiwan kesukaan", "Labelkan bahagian tubuhnya", "Ceritakan kepada kawan", "Kepentingan setiap satunya"]]),
"T1-U06-tumbuhan": ("Bahagian Tumbuhan", "zapin",
 ["Bunga, daun, batang, akar", "Bahagian tumbuhan kita", "Setiap bahagian penting", "Mari kita jaga"],
 [["Akar menyokong pokok", "Menyerap air dari tanah", "Batang mengangkut makanan", "Air dan nutrien juga"],
  ["Daun membuat makanan", "Hijau segar di dahan", "Bunga bertukar menjadi buah", "Dan biji benih di dalamnya"],
  ["Teratai berbunga, paku pakis tidak", "Durian berkayu, betik tidak", "Ros urat jejala, akar tunjang", "Pandan urat selari, akar serabut"],
  ["Pokok bunga raya dan bunga ros", "Banyak ciri yang serupa", "Berbunga, berkayu, urat jejala", "Akar tunjang juga"]]),
"T1-U08-penyerapan": ("Serap, Serap, Serap Air", "pop",
 ["Serap, serap, serap air", "Bahan mana yang menyerap?", "Kain lap menyerap paling banyak", "Kertas tisu paling sedikit"],
 [["Tisu dapur dan kain lap", "Kertas dan sapu tangan", "Semuanya menyerap air", "Basah, tapi menyerap"],
  ["Gelas kaca, sudu logam", "Mainan plastik, klip kertas", "Tidak menyerap air", "Air tetap di atasnya"],
  ["Tuala mengeringkan badan", "Kain lap keringkan tumpahan", "Payung plastik, kasut getah", "Tak menyerap, kita tak basah"],
  ["Mari reka mop mini", "Guna tali yang menyerap air", "Tumpahan air di lantai", "Mop mini mengeringkannya"]]),
"T1-U09-bumi": ("Bumi Kita", "nasyid",
 ["Bumi kita, bumi kita", "Indah dan permai", "Mari kita kenali", "Mari kita sayangi"],
 [["Gunung, bukit dan lembah", "Sungai, pantai dan laut", "Tasik dan kolam juga", "Lapan bentuk muka bumi"],
  ["Tanah kebun ada ranting", "Daun kering, batu dan pasir", "Ada haiwan kecil juga", "Tanah liat butirnya halus"],
  ["Tanah dan air di dalam balang", "Tutup, goncang, tunggu tiga puluh minit", "Pasir mendap dengan cepat", "Tanah liat menjadikan air keruh"],
  ["Batu-batu kecil dan pasir", "Kita buat penapis air", "Air yang keruh tadi", "Menjadi lebih jernih"]]),
"T1-U10-asas-binaan": ("Bentuk dan Bongkah", "tadika",
 ["Kubus, kuboid, piramid, prisma", "Kon, silinder dan sfera", "Tujuh bongkah bentuk asas", "Mari kita bina!"],
 [["Segi tiga, segi empat sama", "Segi empat tepat, bulatan", "Itulah empat bentuk asas", "Mari kita lukiskan"],
  ["Lakar reka bentuk dahulu", "Bentukkan bongkah satu-satu", "Cantumkan menjadi robot", "Namakan bongkah itu"],
  ["Bola berbentuk sfera", "Mudah bergolek bila disepak", "Jam meja berbentuk kuboid", "Terletak elok di atas meja"]]),
# ------------------------------------------------------------------ Tahun 2
"T2-U01-kemahiran-saintifik": ("Saintis Muda", "pop",
 ["Saintis muda, saintis muda", "Kelas, ukur dan siasat", "Catat, lakar, labelkan", "Sains kita hebat!"],
 [["Mengelas itu mengasingkan", "Dan mengumpul ikut ciri", "Itik, penguin, helang berkepak", "Kambing, tenuk, harimau tidak"],
  ["Berat diukur dengan penimbang", "Dalam unit kilogram", "Panjang diukur dengan pembaris", "Dalam unit sentimeter"],
  ["Siput kebun dikendali cermat", "Lakar dan labelkan dia", "Selepas siasatan selesai", "Lepaskan ke tempat asalnya"],
  ["Perhati bunga raya, lakarkan", "Cuci tangan dan peralatan", "Simpan dengan betul dan selamat", "Itulah urutan penyiasatan"]]),
"T2-U02-peraturan-bilik-sains": ("Jaga Bilik Sains", "dikir",
 ["Jaga Bilik Sains, jaga Bilik Sains", "Bersih, kemas, tersusun", "Selamat untuk semua", "Jom kita jaga bersama!"],
 [["Sisa pepejal dan sampah", "Ke manakah dibuang?", "Ke dalam bakul sampah", "Sisa cecair ke dalam singki"],
  ["Jangan buang pepejal ke singki", "Nanti singki tersumbat", "Bawa buku dan alat tulis", "Beg ditinggal di luar"],
  ["Jika ada yang tercedera", "Alat rosak atau pecah", "Beritahu guru segera", "Jangan sentuh kaca pecah"],
  ["Selepas alat digunakan", "Bersihkan alat dan radas", "Simpan di tempat asal", "Dengan kemas dan rapi"]]),
"T2-U03-manusia": ("Saya Membesar", "nasyid",
 ["Saya membesar, saya membesar", "Tinggi dan berat bertambah", "Setiap orang berbeza", "Walaupun umur sama"],
 [["Manusia membiak", "Dengan melahirkan anak", "Bayi, kanak-kanak, remaja", "Akhirnya dewasa"],
  ["Ukur tinggi dengan pembaris dinding", "Berat dengan alat penimbang", "Rekodkan dalam jadual", "Tumbesaran kita berbeza"],
  ["Warna iris mata, warna kulit", "Jenis rambut juga", "Diwarisi daripada ibu, bapa", "Atau keturunannya"],
  ["Rambut Kugan sama", "Seperti rambut datuknya", "Ciri yang diwarisi", "Daripada keluarga"]]),
"T2-U04-haiwan": ("Kitar Hidup Haiwan", "joget",
 ["Telur, berudu, anak katak", "Katak dewasa melompat", "Telur, larva, pupa", "Rama-rama terbang bebas"],
 [["Katak, buaya, nyamuk, itik", "Membiak dengan bertelur", "Kucing, kanggaru, ikan lumba-lumba", "Melahirkan anak"],
  ["Burung, angsa dan penguin", "Bertelur sedikit", "Ikan, katak dan semut", "Bertelur banyak sekali"],
  ["Anak beruang, harimau, belalang", "Menyerupai induknya", "Anak katak dan rama-rama", "Tidak serupa induknya"],
  ["Burung membuat sarang", "Di atas dahan pokok", "Penyu menimbus telur di pasir", "Kucing menyusukan anaknya"]]),
"T2-U05-tumbuhan": ("Tumbuh-tumbuhan", "zapin",
 ["Tumbuh-tumbuhan, tumbuh-tumbuhan", "Penting untuk semua", "Mari kita tanam", "Mari kita jaga"],
 [["Habitat untuk haiwan", "Sumber makanan kita", "Udara untuk bernafas", "Dan sumber ubat juga"],
  ["Biji benih bercambah", "Perlukan air dan udara", "Dan suhu yang sesuai", "Barulah ia bercambah"],
  ["Biji benih bercambah", "Anak pokok membesar", "Pokok berbunga, pokok berbuah", "Tomato merah segar"],
  ["Daun bertambah dan membesar", "Pokok semakin tinggi", "Lilitan batang bertambah", "Tanda tumbesaran"],
  ["Air, udara, cahaya matahari", "Nutrien membantu subur", "Tanpa keperluan asas", "Tumbuhan layu dan mati"]]),
"T2-U06-terang-gelap": ("Terang dan Gelap", "tadika",
 ["Terang, terang, mudah membaca", "Menulis dan melukis", "Gelap, gelap, sukar semua", "Kita perlukan cahaya!"],
 [["Matahari, lampu dan api", "Sumber cahaya kita", "Matahari sumber cahaya", "Semula jadi namanya"],
  ["Cahaya dihalang oleh objek", "Terhasil bayang-bayang", "Kertas tebal bayang jelas", "Plastik jernih tiada bayang"],
  ["Surih dan gunting watak", "Lekatkan pada lidi", "Antara lampu suluh dan layar", "Wayang kertas dimainkan"]]),
"T2-U07-elektrik": ("Litar Lengkap", "pop",
 ["Litar lengkap, mentol menyala", "Arus elektrik mengalir", "Suis terbuka, mentol padam", "Litar tidak lengkap!"],
 [["Sel kering bekal tenaga", "Mentol mengeluarkan cahaya", "Suis sambung dan putuskan litar", "Wayar menyambungkan semua"],
  ["Mentol tak menyala? Mari periksa", "Suis terbuka? Sel kering lemah?", "Mentol rosak atau tak ketat?", "Wayar dipasang tak kemas?"],
  ["Klip kertas, sudu logam, paku, syiling", "Konduktor, arus mengalir", "Pemadam, straw, rod kaca, kayu aiskrim", "Penebat, arus tak mengalir"],
  ["Tukar mentol dengan buzzer", "Litar lengkap, buzzer berbunyi"]]),
"T2-U08-campuran": ("Larut, Larut", "joget",
 ["Larut, larut, gula larut", "Garam pun larut juga", "Gula tidak hilang, ia larut", "Di dalam air"],
 [["Dua atau lebih bahan", "Dicampur menjadi campuran", "Menyisih, mengayak, guna magnet", "Mengapung dan menuras"],
  ["Biji jagung, kacang hijau, beras", "Tidak larut di dalam air", "Masih kelihatan lagi", "Walaupun selepas diaduk"],
  ["Mahu gula larut cepat?", "Guna air yang panas", "Aduk, aduk, aduk", "Gula pasir lebih cepat larut"]]),
"T2-U09-bumi": ("Air dan Udara", "nasyid",
 ["Air menyejat, wap air naik", "Menyejuk, awan terbentuk", "Awan berat, turunlah hujan", "Kitar air berulang"],
 [["Hujan, sungai, tasik, laut", "Dan mata air juga", "Sumber air semula jadi", "Untuk semua hidupan"],
  ["Air mengalir dari tempat tinggi", "Ke tempat yang rendah", "Air terjun, air sungai", "Akhirnya ke laut"],
  ["Aliran air terganggu", "Banjir kilat, nyamuk membiak", "Air sungai berbau", "Jagalah aliran air"],
  ["Udara di sekeliling kita", "Di dalam air dan tanah", "Oksigen untuk bernafas", "Karbon dioksida dihembus"],
  ["Udara bergerak itulah angin", "Layang-layang terbang tinggi", "Kincir berputar, kapal belayar", "Tiup straw, roket terbang"]]),
"T2-U10-teknologi": ("Set Binaan", "tadika",
 ["Pasang, pasang, ikut manual", "Kepala, badan, ekor, kipas", "Dengan betul dan teratur", "Siaplah model kita!"],
 [["Set binaan banyak komponen", "Ada manual bergambar", "Kenal bentuk, warna, bilangan", "Sediakan dengan teratur"],
  ["Rancang dan lakar binaan baharu", "Yang tiada dalam manual", "Bina dan ceritakan", "Fungsinya yang hebat"],
  ["Buka bermula langkah akhir", "Susun ikut bentuk dan warna", "Kira bilangannya", "Simpan dalam kotak dengan kemas"]]),
# ------------------------------------------------------------------ Tahun 3
"T3-U01-kemahiran-saintifik": ("Kemahiran Proses Sains", "pop",
 ["Kelas, ukur, inferens, ramal", "Berkomunikasi dengan jelas", "Kemahiran proses sains", "Saintis bijak dan cerdas!"],
 [["Kelaskan ikut bentuk", "Kelaskan semula ikut warna", "Persamaan dan perbezaan", "Itulah mengelas"],
  ["Panjang diukur dengan pembaris", "Masa dengan jam randik", "Hujung objek di senggat sifar", "Mata tegak dari atas"],
  ["Inferens kesimpulan awal", "Yang munasabah", "Boleh lebih daripada satu", "Perlu disemak lagi"],
  ["Meramal berdasarkan bukti", "Pemerhatian, data, pola", "Bukan tekaan semata-mata", "Ramalan yang bijak"],
  ["Rekod dalam jadual dan graf", "Tembikai paling digemari", "Enam orang murid memilihnya", "Maklumat jadi jelas"]]),
"T3-U02-peraturan-bilik-sains": ("Sebelum, Semasa, Selepas", "dikir",
 ["Sebelum, semasa, selepas", "Patuhi peraturan", "Bilik Sains selamat", "Belajar menyeronokkan"],
 [["Sebelum aktiviti", "Beratur sebelum masuk", "Beg diletak di luar", "Pakai kasut bertutup"],
  ["Buka pintu dan tingkap", "Cahaya dan udara masuk", "Ambil alat dengan cermat", "Ikut arahan guru"],
  ["Jangan makan, jangan minum", "Jangan berlari atau bermain", "Ada kerosakan, beritahu guru", "Jangan conteng meja"],
  ["Selepas aktiviti", "Bersihkan peralatan", "Tutup suis kipas dan lampu", "Jangan membazir elektrik"]]),
"T3-U03-manusia": ("Gigi dan Makanan", "joget",
 ["Berus gigi dua kali sehari", "Guna flos, kurangkan manis", "Periksa gigi setiap enam bulan", "Senyum manis selalu!"],
 [["Gigi kacip memotong", "Gigi taring mengoyakkan", "Gigi geraham melumatkan", "Makanan kita"],
  ["Enamel, dentin dan saraf", "Salur darah di dalamnya", "Gusi memegang gigi", "Itulah struktur gigi"],
  ["Gigi susu dua puluh batang", "Gigi kekal tiga puluh dua", "Gigi kekal enamelnya tebal", "Jagalah sampai tua"],
  ["Nasi, roti, ubi secukupnya", "Buah dan sayur makan banyak", "Ikan, ayam, susu sederhana", "Minyak, gula, garam sedikit"],
  ["Makanan seimbang semua kelas", "Terlalu berlemak, kegemukan", "Terlalu manis, gigi rosak", "Kurang sayur, sembelit"],
  ["Mulut, esofagus, perut", "Usus dan dubur", "Jangan makan sambil berlari", "Nanti tersedak dan sakit perut"]]),
"T3-U04-haiwan": ("Herbivor, Karnivor, Omnivor", "dikir",
 ["Herbivor makan tumbuhan", "Karnivor makan haiwan", "Omnivor makan kedua-duanya", "Itulah tabiat makan"],
 [["Arnab makan apa? Lobak merah dan sawi", "Harimau makan apa? Daging!", "Ayam makan apa?", "Bijirin dan cacing!"],
  ["Herbivor gigi kacip kuat", "Gigi geraham yang besar", "Karnivor gigi taring tajam", "Untuk mengoyakkan daging"],
  ["Omnivor ada kacip, taring, geraham", "Beruang omnivor semula jadi", "Beruang kutub di kawasan berais", "Menjadi karnivor"]]),
"T3-U05-tumbuhan": ("Tumbuhan Membiak", "zapin",
 ["Membiak, membiak, tumbuhan membiak", "Supaya tidak pupus", "Makanan, habitat, oksigen", "Dan kayu sentiasa ada"],
 [["Biji benih, anak pokok", "Batang bawah tanah, daun", "Keratan batang dan spora", "Cara tumbuhan membiak"],
  ["Pokok kangkung membiak", "Biji benih, keratan batang", "Pokok ubi keledek pula", "Keratan batang, batang bawah tanah"],
  ["Kultur tisu untuk pisang, orkid", "Tisu pokok dalam nutrien", "Tut untuk mangga, limau kasturi", "Tanpa menanam biji benih"]]),
"T3-U06-pengukuran": ("Luas dan Isi Padu", "tadika",
 ["Luas, luas, kira petaknya", "Isi padu, ruang yang dipenuhi", "Ukur dengan betul", "Pandai mengira!"],
 [["Luas buku sentimeter persegi", "Luas tikar meter persegi", "Luas negeri Sabah", "Kilometer persegi"],
  ["Satu petak di kertas petak", "Satu sentimeter persegi", "Tiga kali dua, enam petak", "Enam sentimeter persegi"],
  ["Tekap daun pada kertas graf", "Kira petak penuh dan separuh", "Kurang separuh tidak dikira", "Anggarkan luasnya"],
  ["Kotak lohong diisi kubus", "Lapan sentimeter padu", "Silinder penyukat atau bikar", "Mata pada aras meniskus"],
  ["Batu dimasukkan ke dalam air", "Air tersesar sama isi padu", "Tiga puluh tolak dua puluh", "Sepuluh mililiter"]]),
"T3-U07-ketumpatan": ("Timbul atau Tenggelam", "pop",
 ["Timbul, tenggelam, timbul, tenggelam", "Itulah ketumpatan", "Setiap objek dan cecair", "Ketumpatannya berbeza"],
 [["Ranting dan span timbul", "Kurang tumpat daripada air", "Batu dan sabun tenggelam", "Lebih tumpat daripada air"],
  ["Anggur tenggelam di dalam air", "Tambah garam atau gula", "Air menjadi lebih tumpat", "Anggur pun timbul"],
  ["Minyak kurang tumpat", "Sentiasa di atas air", "Jaket keselamatan dan pelampung timbul", "Sauh besi tenggelam menahan bot"]]),
"T3-U08-asid-alkali": ("Asid dan Alkali", "joget",
 ["Asid, alkali, neutral", "Uji dengan penunjuk", "Bukan rasa, bukan sentuh", "Itulah cara saintis"],
 [["Kertas litmus penunjuk", "Asid, litmus biru jadi merah", "Alkali, litmus merah jadi biru", "Neutral tak berubah warna"],
  ["Asid kebanyakannya masam", "Alkali kebanyakannya pahit", "Air kopi pahit, tetapi asid", "Rasa bukan penunjuk"],
  ["Ekstrak kubis ungu", "Merah jambu dalam asid", "Hijau dalam alkali", "Kekal ungu dalam neutral"],
  ["Kunyit dan bunga raya", "Boleh ganti litmus juga", "Kapur alkali bantu petani", "Kurangkan asid tanah kebun"]]),
"T3-U09-sistem-suria": ("Lapan Planet", "nasyid",
 ["Utarid, Zuhrah, Bumi, Marikh", "Musytari, Zuhal, Uranus, Neptun", "Lapan planet dari Matahari", "Ingatlah urutannya"],
 [["Matahari pusat Sistem Suria", "Planet beredar mengelilinginya", "Asteroid di antara", "Marikh dan Musytari"],
  ["Bulan satelit semula jadi", "Bagi Bumi kita", "Meteoroid dan komet", "Ahli Sistem Suria juga"],
  ["Dekat Matahari lebih panas", "Yang jauh lebih sejuk", "Tetapi Zuhrah paling panas", "Atmosfera tebal memerangkap haba"],
  ["Orbit laluan berbentuk elips", "Semakin jauh, semakin lama", "Bumi mengambil masa setahun", "Satu peredaran lengkap"]]),
"T3-U10-mesin": ("Takal Tetap", "dikir",
 ["Tarik ke bawah, tarik ke bawah", "Beban naik ke atas", "Takal tetap membantu", "Kerja jadi mudah"],
 [["Takal mesin ringkas", "Memudahkan angkat beban", "Alur, gandar, roda", "Tali dan beban"],
  ["Naikkan bendera, timba air perigi", "Tarik pukat ke darat", "Angkat bahan binaan", "Kontena dari kapal ke lori"],
  ["Kenal pasti masalah, jana idea", "Lakar, sediakan alat dan bahan", "Bina model takal", "Gantung dan uji"]]),
# ------------------------------------------------------------------ Tahun 4
"T4-U01-kemahiran-saintifik": ("Saintis Penyiasat", "pop",
 ["Ubah satu, ukur satu", "Yang lain kekal sama", "Itulah penyiasatan adil", "Saintis penyiasat!"],
 [["Aiskrim cair ikut masa", "Bentuk berubah, saiz mengecil", "Ruang dan masa", "Perubahan ikut urutan"],
  ["Mentafsir data", "Beri penerangan rasional", "Tempat A paling banyak burung", "Tempat B paling sedikit"],
  ["Definisi secara operasi", "Apa dibuat, apa diperhati", "Air tinggal paling sedikit", "Tisu menyerap paling banyak"],
  ["Dimanipulasi, yang diubah", "Bergerak balas, diukur", "Dimalarkan, kekal sama", "Tiga pemboleh ubah"],
  ["Semakin banyak adukan", "Semakin singkat masa gula melarut", "Hipotesis diterima", "Eksperimen berjaya!"]]),
"T4-U02-manusia": ("Badan Kita Bekerja", "nasyid",
 ["Oksigen masuk, karbon dioksida keluar", "Pertukaran gas di peparu", "Udara bersih, badan sihat", "Bernafaslah dengan tenang"],
 [["Tarik nafas, udara masuk", "Hidung, trakea, peparu", "Hembus nafas, udara keluar", "Peparu, trakea, hidung"],
  ["Kadar pernafasan", "Dada naik turun dalam seminit", "Semakin cergas aktiviti", "Semakin bertambah kadarnya"],
  ["Elakkan asap rokok", "Dan udara tercemar", "Bersenam di tempat", "Yang udaranya bersih"],
  ["Ginjal singkirkan air kencing", "Kulit merembeskan peluh", "Peparu bebaskan karbon dioksida", "Itulah perkumuhan"],
  ["Rangsangan dan gerak balas", "Elak kecederaan", "Arak, gam dan dadah", "Lambatkan gerak balas, jauhilah!"]]),
"T4-U03-haiwan": ("Lima Kelas Vertebrata", "dikir",
 ["Mamalia, reptilia, amfibia", "Burung dan ikan", "Lima kelas vertebrata", "Ada tulang belakang"],
 [["Kucing, buaya, lembu, peparu", "Ikan, ketam, udang, insang", "Cacing, lintah, kulit lembap", "Belalang, kupu-kupu, spirakel"],
  ["Katak di darat guna peparu", "Di dalam air kulit lembap", "Lebih daripada satu", "Organ pernafasan"],
  ["Ular, kuda, burung, ikan, kura-kura", "Vertebrata, ada tulang belakang", "Cacing, belalang, lebah, nyamuk, udang", "Invertebrata, tiada tulang belakang"],
  ["Paus di laut bernafas dengan peparu", "Kelawar terbang tetapi mamalia", "Platipus bertelur, menyusukan anak", "Mamalia istimewa"]]),
"T4-U04-tumbuhan": ("Fotosintesis", "zapin",
 ["Cahaya matahari dan air", "Karbon dioksida, klorofil", "Fotosintesis, buat makanan sendiri", "Tumbuhan hijau hebat!"],
 [["Akar tumbuh ke arah air", "Pucuk ke arah cahaya", "Akar ke arah graviti", "Tumbuhan bergerak balas"],
  ["Pokok semalu disentuh", "Daunnya menguncup", "Perangkap lalat Venus", "Tertutup bila disentuh"],
  ["Klorofil menyerap cahaya", "Air dan karbon dioksida ditukar", "Menjadi glukosa dan oksigen", "Glukosa disimpan sebagai kanji"],
  ["Fotosintesis bekalkan makanan", "Bekalkan oksigen", "Mengekalkan keseimbangan udara", "Untuk semua hidupan"]]),
"T4-U05-cahaya": ("Sifat Cahaya", "pop",
 ["Bergerak lurus, dipantul, dibias", "Cahaya hebat sungguh", "Pelangi di langit biru", "Titisan air membiaskan"],
 [["Cahaya bergerak lurus", "Dari sumber cahaya", "Celah kadbod mesti sebaris", "Barulah sampai ke skrin"],
  ["Lut sinar tiada bayang", "Lut cahaya bayang tak jelas", "Legap bayang-bayang jelas", "Cahaya dihalang objek"],
  ["Objek jauh dari sumber cahaya", "Bayang-bayang mengecil", "Orientasi objek berubah", "Bentuk bayang pun berubah"],
  ["Cermin licin memantulkan cahaya", "Periskop guna dua cermin", "Cermin sisi, cermin cembung", "Cermin pergigian juga"],
  ["Melalui dua medium berbeza", "Arah cahaya berubah", "Itulah pembiasan cahaya", "Pelangi pun terbentuk"]]),
"T4-U06-bunyi": ("Getaran Bunyi", "joget",
 ["Bunyi bergerak ke semua arah", "Loceng didengar dari mana-mana", "Getaran, getaran", "Bunyi di sekeliling kita"],
 [["Seruling ditiup, xilofon diketuk", "Gitar dipetik, biola digesek", "Simbal ditepuk, semua bergetar", "Getaran menghasilkan bunyi"],
  ["Permukaan keras memantulkan bunyi", "Gema di gua dan dewan kosong", "Permukaan lembut", "Menyerap bunyi"],
  ["Muzik, suara, siren ambulans", "Deringan telefon dan sonar", "Bunyi berfaedah", "Membantu kita"],
  ["Bunyi bising ganggu ketenangan", "Terlalu kuat rosakkan pendengaran", "Permaidani, langsir serap bunyi", "Pelindung telinga melindungi"]]),
"T4-U07-tenaga": ("Sembilan Bentuk Tenaga", "pop",
 ["Suria, haba, cahaya, bunyi", "Elektrik, kimia, kinetik", "Keupayaan dan nuklear", "Sembilan bentuk tenaga!"],
 [["Tenaga keupayaan melakukan kerja", "Matahari sumber utama", "Matahari, air, angin, ombak, biojisim", "Boleh dibaharui"],
  ["Petroleum dan gas asli", "Arang batu dan nuklear", "Tidak boleh dibaharui", "Gunakan dengan bijak"],
  ["Tenaga tak boleh dicipta", "Tak boleh dimusnahkan", "Hanya berubah bentuk", "Kimia, elektrik, cahaya di lampu suluh"],
  ["Buka tingkap, kurangkan penyaman udara", "Jalan kaki atau berbasikal", "Naik pengangkutan awam", "Berhemat tenaga"]]),
"T4-U08-bahan": ("Pilih Bahan", "tadika",
 ["Pilih bahan ikut sifatnya", "Pilih bahan ikut kegunaan", "Bahan yang sesuai", "Kerja jadi mudah"],
 [["Getah, kayu, kapas dari tumbuhan", "Bulu, kulit, sutera dari haiwan", "Plastik dan kain sintetik dari petroleum", "Logam, tanah liat, pasir dari batuan"],
  ["Kain kapas menyerap air", "Plastik kalis air", "Kunci logam tenggelam", "Konduktor elektrik"],
  ["Sisip kaca pandangan jelas", "Logam konduktor haba", "Kayu penebat haba", "Getah, belon, spring kenyal"],
  ["Periuk logam alirkan haba", "Gelang getah gerakkan kereta mainan", "Kaca membenarkan cahaya masuk", "Kenal pasti masalah, cetus idea, bina!"]]),
"T4-U09-bumi": ("Siang dan Malam", "nasyid",
 ["Bumi berputar pada paksinya", "Dari barat ke timur", "Dua puluh empat jam sehari", "Siang dan malam silih berganti"],
 [["Graviti menarik objek", "Ke arah pusat bumi", "Tanpa graviti", "Semua terapung di udara"],
  ["Bumi beredar mengelilingi Matahari", "Lengkap dalam setahun", "Tiga ratus enam puluh lima", "Dan suku hari"],
  ["Menghadap Matahari, siang", "Terlindung, malam", "Bayang-bayang pensel berubah", "Paling pendek tengah hari"]]),
"T4-U10-mesin": ("Tujuh Mesin Ringkas", "dikir",
 ["Roda dan gandar, tuas, skru", "Gear dan takal", "Satah condong dan baji", "Tujuh mesin ringkas!"],
 [["Beban, fulkrum dan daya", "Bahagian tuas", "Beban dekat dengan fulkrum", "Daya sedikit diperlukan"],
  ["Gunting pemangkas, skru dan baji", "Kereta sorong, tuas, skru, roda dan gandar", "Basikal, gear, skru, roda dan gandar", "Mesin kompleks namanya"],
  ["Troli guna roda dan gandar", "Papan jadi satah condong", "Beban berat naik ke lori", "Mudah dan pantas"],
  ["Mesin lestari tahan lama", "Mudah dan selamat digunakan", "Tidak mencemarkan alam", "Seperti basikal"]]),
# ------------------------------------------------------------------ Tahun 5
"T5-U01-kemahiran-saintifik": ("Buih Sabun", "pop",
 ["Buih sabun, buih sabun", "Semakin banyak gliserin", "Semakin lama buih pecah", "Hipotesis diterima!"],
 [["Memerhati, mengelas, mengukur", "Inferens dan meramal", "Berkomunikasi, ruang dan masa", "Mentafsir data"],
  ["Dimanipulasikan, kuantiti gliserin", "Bergerak balas, tempoh buih pecah", "Dimalarkan jenis cecair pencuci", "Isi padu air, saiz buih, kelajuan angin"],
  ["Gliserin sedikit, buih cepat pecah", "Gliserin banyak, buih tahan lama", "Catat tempoh dalam jadual", "Bandingkan dan simpulkan"]]),
"T5-U02-manusia": ("Rangka dan Darah", "joget",
 ["Leher, bahu dan siku", "Pergelangan tangan", "Pinggul, lutut, buku lali", "Sendi tempat tulang bertemu"],
 [["Tengkorak, tulang rusuk", "Dan tulang belakang", "Tulang tangan, tulang kaki", "Sistem rangka kita"],
  ["Tengkorak melindungi otak", "Rusuk lindungi jantung, peparu", "Tulang belakang sokong tubuh", "Tangan dan kaki untuk bergerak"],
  ["Darah lebih oksigen", "Peparu, jantung, ke tubuh", "Darah lebih karbon dioksida", "Tubuh, jantung, ke peparu"],
  ["Jagalah semua sistem", "Tubuh berfungsi baik"]]),
"T5-U03-haiwan": ("Kemandirian Haiwan", "dikir",
 ["Rantai makanan bermula", "Dengan pengeluar, tumbuhan hijau", "Anak panah, dimakan oleh", "Tenaga berpindah"],
 [["Cangkerang keras, sengat berbisa", "Sisik keras melindungi", "Cicak memutuskan ekor", "Sotong menyembur dakwat"],
  ["Cuaca sejuk, bulu tebal", "Lapisan lemak, ada yang berhijrah", "Cuaca panas berendam air", "Cuping telinga besar"],
  ["Lindungi telur dan anak", "Supaya spesies terus hidup", "Tidak pupus", "Terus berkembang"],
  ["Beberapa rantai makanan", "Bergabung dalam habitat", "Itulah siratan makanan", "Kolam penuh kehidupan"]]),
"T5-U04-tumbuhan": ("Kemandirian Tumbuhan", "zapin",
 ["Angin, air, haiwan, manusia", "Letupan juga", "Biji benih dipencarkan", "Tumbuhan terus hidup"],
 [["Duri tajam dan getah", "Bulu halus dan racun", "Bau busuk juga", "Tumbuhan melindungi diri"],
  ["Kelapa batang mudah lentur", "Tahan angin kencang", "Kaktus, tomato, kunyit, keladi", "Kurangkan kehilangan air"],
  ["Pokok pain berdaun jarum", "Kulit batang tebal", "Tahan iklim sejuk", "Terus hidup subur"],
  ["Pencaran biji benih", "Mengelakkan kepupusan", "Sumber makanan", "Terus berkekalan"]]),
"T5-U05-elektrik": ("Bersiri dan Selari", "pop",
 ["Litar bersiri satu laluan", "Litar selari banyak laluan", "Mentol selari lebih cerah", "Elektrik mengalir!"],
 [["Stesen jana kuasa, sel suria", "Sel kering, dinamo", "Akumulator dan penjana", "Sumber tenaga elektrik"],
  ["Simbol mewakili komponen", "Lakarkan rajah litar", "Tambah sel kering, mentol lebih cerah", "Tambah mentol bersiri, lebih malap"],
  ["Padamkan lampu bila tak guna", "Tangan mesti kering", "Satu plag satu soket", "Selamat dan jimat"]]),
"T5-U06-haba": ("Haba dan Suhu", "tadika",
 ["Panas mengembang, sejuk mengecut", "Pepejal, cecair dan gas", "Terima haba, hilang haba", "Bahan pun berubah"],
 [["Termometer mengukur suhu", "Darjah Celsius unitnya", "Mata pada aras cecair", "Baca dengan betul"],
  ["Air dipanaskan, suhu naik", "Seratus darjah mendidih, kekal", "Dibiarkan, haba hilang", "Sampai suhu bilik"],
  ["Celah di sambungan jambatan", "Celah di landasan", "Kabel elektrik dipasang kendur", "Tak putus bila sejuk"]]),
"T5-U07-pengaratan": ("Jauhi Karat", "joget",
 ["Air dan udara", "Punca pengaratan", "Halang besi bersentuhan", "Karat tak datang"],
 [["Objek besi boleh berkarat", "Perang kemerahan warnanya", "Permukaan kasar", "Rapuh dan lemah"],
  ["Cat dan gris", "Salutan plastik", "Saduran logam", "Lapisan pelindung"],
  ["Paku dalam air dan udara", "Lama-lama berkarat", "Paku yang dicat", "Kekal berkilat"]]),
"T5-U08-jirim": ("Tiga Keadaan Jirim", "pop",
 ["Peleburan, pepejal jadi cecair", "Pendidihan, cecair jadi gas", "Kondensasi, gas jadi cecair", "Pembekuan, cecair jadi pepejal"],
 [["Jirim ada jisim", "Memenuhi ruang", "Pepejal, cecair, gas", "Tiga keadaan jirim"],
  ["Ais mencair, peleburan", "Air jadi ais, pembekuan", "Baju basah kering, penyejatan", "Titisan di luar gelas, kondensasi"],
  ["Penyejatan, kondensasi", "Hujan pun turun", "Air mengalir ke sungai dan laut", "Kitaran air berterusan"]]),
"T5-U09-fasa-bulan": ("Fasa Bulan dan Buruj", "nasyid",
 ["Anak bulan, bulan sabit", "Bulan separa, hampir purnama", "Bulan purnama bersinar", "Kemudian kembali semula"],
 [["Bulan memantulkan cahaya Matahari", "Beredar mengelilingi Bumi", "Bahagian yang disinari", "Berubah setiap malam"],
  ["Buruj gugusan bintang", "Corak di langit malam", "Biduk dan Belantik", "Pari dan Skorpio"],
  ["Biduk tunjuk arah utara", "Pari tunjuk selatan", "Biduk musim menanam", "Skorpio musim menuai"]]),
"T5-U10-mesin": ("Alat Lestari", "dikir",
 ["Alat lestari, bahan sesuai", "Tahan lama, mudah diselenggara", "Kos rendah, mesra alam", "Selamat digunakan"],
 [["Pengokot, tuas dan baji", "Pengasah pensel, roda, gandar, baji", "Pemotong kuku, tuas dan baji", "Jam tangan, gear, skru, roda dan gandar"],
  ["Tong sampah beroda", "Mudah digerakkan", "Ruangnya dibahagi", "Kitar semula dan kompos"],
  ["Lakar reka bentuk", "Labelkan bahan dan bahagian", "Terangkan ciri lestari", "Bentangkan hasil"]]),
# ------------------------------------------------------------------ Tahun 6
"T6-U01-kemahiran-saintifik": ("Kereta Belon", "pop",
 ["Semakin besar belon", "Semakin jauh kereta bergerak", "Hipotesis diterima", "Eksperimen berjaya!"],
 [["Memerhati, mengelas", "Mengukur, guna nombor", "Inferens, meramal, berkomunikasi", "Kemahiran asas"],
  ["Ruang dan masa, mentafsir data", "Definisi secara operasi", "Kawal pemboleh ubah, hipotesis", "Mengeksperimen, bersepadu"],
  ["Dimanipulasikan, saiz belon", "Bergerak balas, jarak kereta", "Dimalarkan bentuk dan saiz", "Jisim kereta belon"]]),
"T6-U02-manusia": ("Pembiakan dan Saraf", "nasyid",
 ["Otak dan saraf tunjang", "Sistem saraf pusat", "Saraf periferi hantar isyarat", "Otak beri arahan"],
 [["Testis menghasilkan sperma", "Ovari menghasilkan ovum", "Tiub Fallopio tempat persenyawaan", "Uterus tempat embrio berkembang"],
  ["Sperma bercantum dengan ovum", "Terbentuklah zigot", "Embrio, fetus dalam uterus", "Sembilan bulan, bayi lahir"],
  ["Menari dan makan, tindakan terkawal", "Jantung berdenyut, luar kawal", "Terpijak benda tajam", "Refleks menarik kaki"],
  ["Makanan seimbang, tidur cukup", "Elakkan minuman beralkohol", "Pakai topi keledar", "Amalkan postur betul"]]),
"T6-U03-mikroorganisma": ("Mikroorganisma", "joget",
 ["Roti, yogurt dan tempe", "Antibiotik dan vaksin", "Baja organik juga", "Mikroorganisma berguna"],
 [["Fungi, bakteria, alga", "Protozoa dan virus", "Kumpulan mikroorganisma", "Dilihat dengan mikroskop"],
  ["Mikroorganisma bernafas", "Bergerak dan bertumbuh", "Perlu air, udara, nutrien", "Suhu dan keasidan sesuai"],
  ["Tetapi makanan boleh rosak", "Gigi pula reput", "Penyakit merebak", "Berhati-hatilah"]]),
"T6-U04-interaksi-hidupan": ("Interaksi Hidupan", "dikir",
 ["Mutualisme, sama-sama untung", "Parasitisme, perumah rugi", "Komensalisme, satu untung", "Yang lain tak terjejas"],
 [["Citah pemangsa", "Rusa mangsanya", "Pemangsa memburu", "Mangsa diburu"],
  ["Sama spesies, intraspesies", "Lain spesies, interspesies", "Rebut makanan, air", "Tempat tinggal dan pasangan"],
  ["Tumbuhan juga bersaing", "Air dan cahaya matahari", "Nutrien dan ruang", "Yang terhad"]]),
"T6-U05-pemuliharaan": ("Selamatkan Hidupan", "nasyid",
 ["Pelihara dan pulihara", "Selamatkan hidupan", "Untuk masa depan", "Bumi kita bersama"],
 [["Burung dodo, mamot, dinosaur", "Telah pupus", "Gajah, badak sumbu, orang utan", "Harimau Malaya diancam kepupusan"],
  ["Bunga pakma juga terancam", "Pemusnahan habitat, pemburuan haram", "Pencemaran, bencana alam", "Dan pemanasan global"],
  ["Pemeliharaan kekalkan keadaan asal", "Pemuliharaan kembalikan asal", "Tanam semula pokok", "Bina pusat pemuliharaan penyu"]]),
"T6-U06-daya": ("Daya dan Geseran", "pop",
 ["Geseran, geseran", "Permukaan kasar, geseran besar", "Minyak, bedak, roda kurangkan", "Grip, bunga tayar tambahkan"],
 [["Daya tarikan atau tolakan", "Tarik, objek mendekati kita", "Tolak, objek menjauhi kita", "Itulah daya"],
  ["Daya ubah bentuk, arah, kelajuan", "Gerakkan objek pegun", "Hentikan objek bergerak", "Hebatnya daya"],
  ["Zarah udara berlanggar", "Tekanan udara terhasil", "Semakin tinggi dari aras laut", "Semakin rendah tekanannya"]]),
"T6-U07-kelajuan": ("Formula Kelajuan", "joget",
 ["Kelajuan, jarak bahagi masa", "Jarak, kelajuan darab masa", "Masa, jarak bahagi kelajuan", "Formula kelajuan!"],
 [["Jarak yang sama", "Yang laju masa singkat", "Masa yang sama", "Yang laju pergi jauh"],
  ["Landasan semakin tinggi", "Guli semakin laju", "Masa semakin singkat", "Sampai ke hujung landasan"],
  ["Sentimeter per saat", "Meter per saat", "Kilometer per jam", "Unit kelajuan"]]),
"T6-U08-pengawetan-makanan": ("Awet Makanan", "zapin",
 ["Kawal suhu, singkir air", "Halang udara, buat berasid", "Mikroorganisma dilambatkan", "Makanan tahan lama"],
 [["Susu berbuih dan berketul", "Roti bertompok kehitaman", "Buah berkulat, daging kehitaman", "Ikan melekit dan lembik"],
  ["Ikan kering, pengeringan", "Jem durian, pendidihan", "Telur masin, pemasinan", "Susu, pempasteuran"],
  ["Sardin, pengetinan", "Epal, pelilinan", "Cili kering kita buat", "Kaedah pengawetan"],
  ["Elakkan pembaziran", "Ada makanan di luar musim", "Mudah dieksport", "Sedia untuk dimakan"]]),
"T6-U09-bahan-buangan": ("Amalan 5R", "dikir",
 ["Tolak, kurangkan, guna semula", "Kitar semula, baiki", "Amalan lima R", "Selamatkan bumi"],
 [["Sisa makanan, kertas, daun kering", "Terbiodegradasi", "Plastik, logam, kaca, sisa toksik", "Tidak terbiodegradasi"],
  ["Asingkan kaca dan kertas", "Plastik dan logam", "Sisa toksik, sisa makanan", "Ikut jenisnya"],
  ["Buang sampah merata-rata", "Air dan udara tercemar", "Hidupan akuatik terancam", "Longkang tersumbat, banjir kilat"]]),
"T6-U10-gerhana": ("Gerhana", "nasyid",
 ["Umbra sangat gelap", "Penumbra separa gelap", "Cahaya bergerak lurus", "Tak menembusi objek legap"],
 [["Matahari, Bumi, Bulan", "Dalam satu garis lurus", "Bumi di tengah, bulan purnama", "Gerhana Bulan berlaku"],
  ["Matahari, Bulan, Bumi", "Bulan pula di tengah", "Semasa bulan baharu", "Gerhana Matahari berlaku"],
  ["Orbit Bulan condong", "Gerhana tak setiap bulan", "Jangan lihat Matahari dengan mata kasar", "Guna cermin mata khas gerhana"]]),
"T6-U11-galaksi": ("Galaksi Bima Sakti", "pop",
 ["Bima Sakti galaksi kita", "Pilin berpalang bentuknya", "Matahari sebutir bintang", "Bumi satu daripada lapan planet"],
 [["Berjuta-juta bintang", "Gas, debu dan jirim lain", "Berpilin, elips", "Tidak sekata"],
  ["Sistem Suria di pinggir", "Satu lengan berpilin", "Dari sisi cakera nipis", "Membonjol di tengah"],
  ["Bumi lebih kecil daripada Sistem Suria", "Sistem Suria kecil di Bima Sakti", "Alam semesta", "Berbilion-bilion galaksi"]]),
"T6-U12-kestabilan-kekuatan": ("Stabil dan Kuat", "joget",
 ["Kekuda rangka segi tiga", "Lengkungan melengkung", "Kubah hemisfera", "Kuat menyokong beban"],
 [["Semakin rendah binaan", "Semakin stabil", "Semakin luas tapaknya", "Semakin stabil"],
  ["Penyedut besi paling kuat", "Penyedut plastik di tengah", "Penyedut kertas paling lemah", "Kekuatan bahan berbeza"],
  ["Binaan kuat dan stabil", "Tak mudah rosak", "Jimat kos baik pulih", "Selamat dan tahan lama"]]),
"T6-U13-teknologi": ("Teknologi Kita", "pop",
 ["Teknologi, teknologi", "Memudahkan kehidupan", "Gunakan dengan bijak", "Untuk masa depan"],
 [["Mikroskop lihat objek seni", "Teleskop lihat yang jauh", "Stetoskop dengar bunyi perlahan", "Telefon hubungi dari jauh"],
  ["Dron bantu pertanian", "Sinar-X dan MRI di hospital", "Kapal terbang, kereta api laju", "Internet maklumat pantas"],
  ["Tapi boleh mencemarkan alam", "Ketagihan dan data diceroboh", "Jika tidak digunakan", "Dengan bijaksana"],
  ["Dron membaja, meracun rumpai", "Jimat masa dan tenaga", "Bateri dron dilupuskan", "Dengan cara betul"]]),
}


def lyrics(chorus, verses):
    """[Verse 1] [Chorus] then a chorus after every two more verses, and always at the end (chorus None = verses only)."""
    if chorus is None:
        return "\n\n".join(f"[Verse {i}]\n" + "\n".join(v) for i, v in enumerate(verses, 1))
    out = [("Verse 1", verses[0]), ("Chorus", chorus)]
    for i, v in enumerate(verses[1:], 2):
        out.append((f"Verse {i}", v))
        if i % 2 == 1:
            out.append(("Chorus", chorus))
    if out[-1][0] != "Chorus":
        out.append(("Chorus", chorus))
    return "\n\n".join(f"[{t}]\n" + "\n".join(lines) for t, lines in out)


if __name__ == "__main__":
    for gid, (title, style, chorus, verses) in SONGS.items():
        assert os.path.isdir(os.path.join(ROOT, "games", gid)), gid
        assert len(verses) <= 9, gid  # [Verse N] tags are single digit
        p = os.path.join(ROOT, "games", gid, "assets", "lagu.json")
        old = json.load(open(p, encoding="utf-8")) if os.path.exists(p) else {}
        d = {"title": title, "style": style, "lyrics": lyrics(chorus, verses), **{k: old[k] for k in ("duration", "bpm", "voice") if k in old}}
        open(p, "w", encoding="utf-8").write(json.dumps(d, ensure_ascii=False, indent=2) + "\n")
    print(len(SONGS), "lagu.json written")
